;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	asm-comment
	backward-sexp
	beginning-of-buffer
	beginning-of-visual-line
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-star
	c-indent-line-or-region
	delete-pair
	delete-word
	electric-pair-delete-pair
	end-of-buffer
	end-of-visual-line
	eshell-bol
	eshell-next-matching-input-from-input
	forward-sexp
	ido-switch-buffer
	indent-for-tab-command
	indent-tabs-mode
	magit-copy-buffer-revision
	multiple-cursors-mode
	org-cycle
	org-delete-char
	org-end-of-line
	org-force-self-insert
	org-self-insert-command
	org-yank
	overwrite-mode
	previous-buffer
	scroll-down-line
	whole-line-or-region-comment-dwim-2
	whole-line-or-region-kill-ring-save
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-pound
	describe-key-briefly
	eshell-previous-matching-input-from-input
	eval-last-sexp
	goto-line
	ignore
	org-ctrl-c-ctrl-c
	previous-window-any-frame
	shell-command
	symbol-overlay-put
	whole-line-or-region-kill-region
	))
